### ISSUE TITLE
Failed to install 'cordova-android-play-services-gradle-release'

### ISSUE THREAD

**Issue by chrillewoodz** [dpa99c/cordova-android-play-services-gradle-release#6]
I was unable to install your plugin when I ran `phonegap plugin add cordova-android-play-services-gradle-release`.

```
Failed to install 'cordova-android-play-services-gradle-release': Error: /Users/banana-man/my-projects/preview/platforms/android/gradlew: Command failed with exit code 1
    at ChildProcess.whenDone (/Users/banana-man/my-projects/preview/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)


Error: /Users/banana-man/my-projects/preview/platforms/android/gradlew: Command failed with exit code 1
```

**Comment by dpa99c** [comment]
Check which version of the Phonegap CLI you are using - the plugin requires installation with the `cordova-fetch` mechanism - see the [installation notes](https://github.com/dpa99c/cordova-android-play-services-gradle-release#installation).

Also run the command with the `--verbose` argument which should give additional details about the error.

**Comment by dpa99c** [comment]
Closed due to no response from OP
